version: '3.8'
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: php-fpm
    volumes:
      - .:/app
    ports:
      - 8000:8000

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./config/ngnix/ngnix.conf:/etc/nginx/conf.d/default.conf
    networks:
        - laravel-exa

#   queue:
#     container_name: Queue
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: 'php artisan queue:work'
#     depends_on:
#       - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}" # Altere para a senha que deseja definir para o usuário root
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 6808:3306

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: PhpMyAdmin
#     links:
#       - db
#     environment:
#       PMA_HOST: db
#       PMA_PORT: 3306
#       PMA_ARBITRARY: 1
#     restart: always
#     ports:
#        ports:
#         - 8081:80
#         - 3307:3306

#   mailpit:
#     image: axllent/mailpit
#     container_name: MailPit
#     ports:
#       - "1025:1025"
#       - "8025:8025"
#     networks:
#       - laravel-exa

networks:
  laravel-exa:
    driver: bridge

volumes:
  db:
    driver: local
